export const FALLBACK_PHRASES = [
  "Pretty please with a cherry? 🍒",
  "Don't break my heart! 💔",
  "I'll be so sad... 🥺",
  "But I love you so much! 💖",
  "I'm gonna cry... 😭",
  "You're my favorite person! 🌟",
  "Please say yes, cutie! 🥺",
  "I promise to be good! 😇",
  "Don't be mean to me! 😢",
  "My heart needs you! ❤️",
  "Just one chance? 🙏",
  "Look at this puppy face! 🐶",
  "But we are soulmates! 💑",
  "I'll give you cookies! 🍪",
  "You are my sunshine! ☀️",
  "Don't let me go! 🏃‍♂️",
  "I'll love you forever! ♾️",
  "Be my player 2? 🎮",
  "We'd be so cute together! 🥰",
  "Please please please! 🥺"
];